# Generated by Django 4.2.1 on 2024-02-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fancynumber_app', '0003_delete_price_fancyphonenumber_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fancyphonenumber',
            name='price_range',
            field=models.CharField(default=22, max_length=50),
            preserve_default=False,
        ),
    ]
