# Generated by Django 4.2.1 on 2024-02-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fancynumber_app', '0004_fancyphonenumber_price_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fancyphonenumber',
            name='price_range',
        ),
        migrations.AlterField(
            model_name='fancyphonenumber',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
